export const UPDATE_REACTANT = "UPDATE_REACTANT";
export const ADD_REACTANT = "ADD_REACTANT";
export const REMOVE_REACTANT = "REMOVE_REACTANT";
export const SET_CHEMICAL_REACTIONS_HISTORY = "SET_CHEMICAL_REACTIONS_HISTORY";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const RESET_ALL = "RESET_ALL";