export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const SET_ERROR_TRUE = "SET_ERROR_TRUE";
export const SET_ERROR_FALSE = "SET_ERROR_FALSE";
export const SET_SUCCESS_TRUE = "SET_SUCCESS_TRUE";
export const SET_SUCCESS_FALSE = "SET_SUCCESS_FALSE";