// export const groupsData = [
//   {
//     id: 1,
//     elements: [
//       {
//         symbol: "H",
//         atomicNumber: 1,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "1.008",
//         name: "Hydrogen",
//       },
//       {
//         symbol: "Li",
//         atomicNumber: 3,
//         category: "alkali metal",
//         color: "red",
//         atomicMass: "6.94",
//         name: "Lithium",
//       },
//       {
//         symbol: "Na",
//         atomicNumber: 11,
//         category: "alkali metal",
//         color: "red",
//         atomicMass: "22.990",
//         name: "Sodium",
//       },
//       {
//         symbol: "K",
//         atomicNumber: 19,
//         category: "alkali metal",
//         color: "red",
//         atomicMass: "39.098",
//         name: "Potassium",
//       },
//       {
//         symbol: "Rb",
//         atomicNumber: 37,
//         category: "alkali metal",
//         color: "red",
//         atomicMass: "85.468",
//         name: "Rubidium",
//       },
//       {
//         symbol: "Cs",
//         atomicNumber: 55,
//         category: "alkali metal",
//         color: "red",
//         atomicMass: "132.905",
//         name: "Caesium",
//       },
//       {
//         symbol: "Fr",
//         atomicNumber: 87,
//         category: "alkali metal",
//         color: "red",
//         atomicMass: "(223)",
//         name: "Francium",
//       },
//     ],
//   },
//   {
//     id: 2,
//     elements: [
//       {
//         symbol: "Be",
//         atomicNumber: 4,
//         category: "alkaline earth metal",
//         color: "orange",
//         atomicMass: "9.0122",
//         name: "Beryllium",
//       },
//       {
//         symbol: "Mg",
//         atomicNumber: 12,
//         category: "alkaline earth metal",
//         color: "orange",
//         atomicMass: "24.305",
//         name: "Magnesium",
//       },
//       {
//         symbol: "Ca",
//         atomicNumber: 20,
//         category: "alkaline earth metal",
//         color: "orange",
//         atomicMass: "40.078",
//         name: "Calcium",
//       },
//       {
//         symbol: "Sr",
//         atomicNumber: 38,
//         category: "alkaline earth metal",
//         color: "orange",
//         atomicMass: "87.62",
//         name: "Strontium",
//       },
//       {
//         symbol: "Ba",
//         atomicNumber: 56,
//         category: "alkaline earth metal",
//         color: "orange",
//         atomicMass: "137.327",
//         name: "Barium",
//       },
//       {
//         symbol: "Ra",
//         atomicNumber: 88,
//         category: "alkaline earth metal",
//         color: "orange",
//         atomicMass: "(226)",
//         name: "Radium",
//       },
//     ],
//   },
//   {
//     id: 3,
//     elements: [
//       {
//         symbol: "Sc",
//         atomicNumber: 21,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "44.956",
//         name: "Scandium",
//       },
//       {
//         symbol: "Y",
//         atomicNumber: 39,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "88.906",
//         name: "Yttrium",
//       },
//       {
//         symbol: "La",
//         atomicNumber: "57-71",
//         category: "lanthanides",
//         color: "lightblue",
//         atomicMass: "138.91",
//         name: "Lanthanides",
//       },
//       {
//         symbol: "Ac",
//         atomicNumber: "89-103",
//         category: "actinide",
//         color: "lightblue",
//         atomicMass: "(227)",
//         name: "Actinides",
//       },
//     ],
//   },
//   {
//     id: 4,
//     elements: [
//       {
//         symbol: "Ti",
//         atomicNumber: 22,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "47.867",
//         name: "Titanium",
//       },
//       {
//         symbol: "Zr",
//         atomicNumber: 40,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "91.224",
//         name: "Zirconium",
//       },
//       {
//         symbol: "Hf",
//         atomicNumber: 72,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "178.49",
//         name: "Hafnium",
//       },
//       {
//         symbol: "Rf",
//         atomicNumber: 104,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(267)",
//         name: "Rutherfordium",
//       },
//     ],
//   },
//   {
//     id: 5,
//     elements: [
//       {
//         symbol: "V",
//         atomicNumber: 23,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "50.942",
//         name: "Vanadium",
//       },
//       {
//         symbol: "Nb",
//         atomicNumber: 41,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "92.906",
//         name: "Niobium",
//       },
//       {
//         symbol: "Ta",
//         atomicNumber: 73,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "180.95",
//         name: "Tantalum",
//       },
//       {
//         symbol: "Db",
//         atomicNumber: 105,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(270)",
//         name: "Dubnium",
//       },
//     ],
//   },
//   {
//     id: 6,
//     elements: [
//       {
//         symbol: "Cr",
//         atomicNumber: 24,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "51.996",
//         name: "Chromium",
//       },
//       {
//         symbol: "Mo",
//         atomicNumber: 42,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "95.95",
//         name: "Molybdenum",
//       },
//       {
//         symbol: "W",
//         atomicNumber: 74,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "183.84",
//         name: "Tungsten",
//       },
//       {
//         symbol: "Sg",
//         atomicNumber: 106,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(271)",
//         name: "Seaborgium",
//       },
//     ],
//   },
//   {
//     id: 7,
//     elements: [
//       {
//         symbol: "Mn",
//         atomicNumber: 25,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "54.938",
//         name: "Manganese",
//       },
//       {
//         symbol: "Tc",
//         atomicNumber: 43,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(98)",
//         name: "Technetium",
//       },
//       {
//         symbol: "Re",
//         atomicNumber: 75,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "186.21",
//         name: "Rhenium",
//       },
//       {
//         symbol: "Bh",
//         atomicNumber: 107,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(270)",
//         name: "Bohrium",
//       },
//     ],
//   },
//   {
//     id: 8,
//     elements: [
//       {
//         symbol: "Fe",
//         atomicNumber: 26,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "55.845",
//         name: "Iron",
//       },
//       {
//         symbol: "Ru",
//         atomicNumber: 44,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "101.07",
//         name: "Ruthenium",
//       },
//       {
//         symbol: "Os",
//         atomicNumber: 76,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "190.23",
//         name: "Osmium",
//       },
//       {
//         symbol: "Hs",
//         atomicNumber: 108,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(277)",
//         name: "Hassium",
//       },
//     ],
//   },
//   {
//     id: 9,
//     elements: [
//       {
//         symbol: "Co",
//         atomicNumber: 27,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "58.933",
//         name: "Cobalt",
//       },
//       {
//         symbol: "Rh",
//         atomicNumber: 45,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "102.91",
//         name: "Rhodium",
//       },
//       {
//         symbol: "Ir",
//         atomicNumber: 77,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "192.22",
//         name: "Iridium",
//       },
//       {
//         symbol: "Mt",
//         atomicNumber: 109,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(278)",
//         name: "Meitnerium",
//       },
//     ],
//   },
//   {
//     id: 10,
//     elements: [
//       {
//         symbol: "Ni",
//         atomicNumber: 28,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "58.693",
//         name: "Nickel",
//       },
//       {
//         symbol: "Pd",
//         atomicNumber: 46,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "106.42",
//         name: "Palladium",
//       },
//       {
//         symbol: "Pt",
//         atomicNumber: 78,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "195.08",
//         name: "Platinum",
//       },
//       {
//         symbol: "Ds",
//         atomicNumber: 110,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(281)",
//         name: "Darmstadtium",
//       },
//     ],
//   },
//   {
//     id: 11,
//     elements: [
//       {
//         symbol: "Cu",
//         atomicNumber: 29,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "63.546",
//         name: "Copper",
//       },
//       {
//         symbol: "Ag",
//         atomicNumber: 47,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "107.87",
//         name: "Silver",
//       },
//       {
//         symbol: "Au",
//         atomicNumber: 79,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "196.97",
//         name: "Gold",
//       },
//       {
//         symbol: "Rg",
//         atomicNumber: 111,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(282)",
//         name: "Roentgenium",
//       },
//     ],
//   },
//   {
//     id: 12,
//     elements: [
//       {
//         symbol: "Zn",
//         atomicNumber: 30,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "65.38",
//         name: "Zinc",
//       },
//       {
//         symbol: "Cd",
//         atomicNumber: 48,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "112.41",
//         name: "Cadmium",
//       },
//       {
//         symbol: "Hg",
//         atomicNumber: 80,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "200.59",
//         name: "Mercury",
//       },
//       {
//         symbol: "Cn",
//         atomicNumber: 112,
//         category: "transition metal",
//         color: "blue",
//         atomicMass: "(285)",
//         name: "Copernicium",
//       },
//     ],
//   },
//   {
//     id: 13,
//     elements: [
//       {
//         symbol: "B",
//         atomicNumber: 5,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "10.81",
//         name: "Boron",
//       },
//       {
//         symbol: "Al",
//         atomicNumber: 13,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "26.982",
//         name: "Aluminium",
//       },
//       {
//         symbol: "Ga",
//         atomicNumber: 31,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "69.723",
//         name: "Gallium",
//       },
//       {
//         symbol: "In",
//         atomicNumber: 49,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "114.82",
//         name: "Indium",
//       },
//       {
//         symbol: "Tl",
//         atomicNumber: 81,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "204.38",
//         name: "Thallium",
//       },
//       {
//         symbol: "Nh",
//         atomicNumber: 113,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "(286)",
//         name: "Nihonium",
//       },
//     ],
//   },
//   {
//     id: 14,
//     elements: [
//       {
//         symbol: "C",
//         atomicNumber: 6,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "12.011",
//         name: "Carbon",
//       },
//       {
//         symbol: "Si",
//         atomicNumber: 14,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "28.085",
//         name: "Silicon",
//       },
//       {
//         symbol: "Ge",
//         atomicNumber: 32,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "72.63",
//         name: "Germanium",
//       },
//       {
//         symbol: "Sn",
//         atomicNumber: 50,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "118.71",
//         name: "Tin",
//       },
//       {
//         symbol: "Pb",
//         atomicNumber: 82,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "207.2",
//         name: "Lead",
//       },
//       {
//         symbol: "Fl",
//         atomicNumber: 114,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "(289)",
//         name: "Flerovium",
//       },
//     ],
//   },
//   {
//     id: 15,
//     elements: [
//       {
//         symbol: "N",
//         atomicNumber: 7,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "14.007",
//         name: "Nitrogen",
//       },
//       {
//         symbol: "P",
//         atomicNumber: 15,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "30.974",
//         name: "Phosphorus",
//       },
//       {
//         symbol: "As",
//         atomicNumber: 33,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "74.922",
//         name: "Arsenic",
//       },
//       {
//         symbol: "Sb",
//         atomicNumber: 51,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "121.76",
//         name: "Antimony",
//       },
//       {
//         symbol: "Bi",
//         atomicNumber: 83,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "208.98",
//         name: "Bismuth",
//       },
//       {
//         symbol: "Mc",
//         atomicNumber: 115,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "(290)",
//         name: "Moscovium",
//       },
//     ],
//   },
//   {
//     id: 16,
//     elements: [
//       {
//         symbol: "O",
//         atomicNumber: 8,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "15.999",
//         name: "Oxygen",
//       },
//       {
//         symbol: "S",
//         atomicNumber: 16,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "32.06",
//         name: "Sulfur",
//       },
//       {
//         symbol: "Se",
//         atomicNumber: 34,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "78.971",
//         name: "Selenium",
//       },
//       {
//         symbol: "Te",
//         atomicNumber: 52,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "127.60",
//         name: "Tellurium",
//       },
//       {
//         symbol: "Po",
//         atomicNumber: 84,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "(209)",
//         name: "Polonium",
//       },
//       {
//         symbol: "Lv",
//         atomicNumber: 116,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "(293)",
//         name: "Livermorium",
//       },
//     ],
//   },
//   {
//     id: 17,
//     elements: [
//       {
//         symbol: "F",
//         atomicNumber: 9,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "18.998",
//         name: "Fluorine",
//       },
//       {
//         symbol: "Cl",
//         atomicNumber: 17,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "35.45",
//         name: "Chlorine",
//       },
//       {
//         symbol: "Br",
//         atomicNumber: 35,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "79.904",
//         name: "Bromine",
//       },
//       {
//         symbol: "I",
//         atomicNumber: 53,
//         category: "nonmetal",
//         color: "green",
//         atomicMass: "126.90",
//         name: "Iodine",
//       },
//       {
//         symbol: "At",
//         atomicNumber: 85,
//         category: "metalloid",
//         color: "yellow",
//         atomicMass: "(210)",
//         name: "Astatine",
//       },
//       {
//         symbol: "Ts",
//         atomicNumber: 117,
//         category: "post-transition metal",
//         color: "purple",
//         atomicMass: "(294)",
//         name: "Tennessine",
//       },
//     ],
//   },
//   {
//     id: 18,
//     elements: [
//       {
//         symbol: "He",
//         atomicNumber: 2,
//         category: "noble gas",
//         color: "pink",
//         atomicMass: "4.0026",
//         name: "Helium",
//       },
//       {
//         symbol: "Ne",
//         atomicNumber: 10,
//         category: "noble gas",
//         color: "pink",
//         atomicMass: "20.180",
//         name: "Neon",
//       },
//       {
//         symbol: "Ar",
//         atomicNumber: 18,
//         category: "noble gas",
//         color: "pink",
//         atomicMass: "39.95",
//         name: "Argon",
//       },
//       {
//         symbol: "Kr",
//         atomicNumber: 36,
//         category: "noble gas",
//         color: "pink",
//         atomicMass: "83.798",
//         name: "Krypton",
//       },
//       {
//         symbol: "Xe",
//         atomicNumber: 54,
//         category: "noble gas",
//         color: "pink",
//         atomicMass: "131.29",
//         name: "Xenon",
//       },
//       {
//         symbol: "Rn",
//         atomicNumber: 86,
//         category: "noble gas",
//         color: "pink",
//         atomicMass: "(222)",
//         name: "Radon",
//       },
//       {
//         symbol: "Og",
//         atomicNumber: 118,
//         category: "noble gas",
//         color: "pink",
//         atomicMass: "(294)",
//         name: "Oganesson",
//       },
//     ],
//   },
// ];

export const LanthanidesActinidesSeries = [
  {
    id: 19,
    elements: [
      {
        symbol: "La",
        atomicNumber: 57,
        category: "lanthanide",
        color: "red",
        atomicMass: "138.91",
        name: "Lanthanum",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ce",
        atomicNumber: 58,
        category: "lanthanide",
        color: "red",
        atomicMass: "140.12",
        name: "Cerium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pr",
        atomicNumber: 59,
        category: "lanthanide",
        color: "red",
        atomicMass: "140.91",
        name: "Praseodymium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Nd",
        atomicNumber: 60,
        category: "lanthanide",
        color: "red",
        atomicMass: "144.24",
        name: "Neodymium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pm",
        atomicNumber: 61,
        category: "lanthanide",
        color: "red",
        atomicMass: "(145)",
        name: "Promethium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sm",
        atomicNumber: 62,
        category: "lanthanide",
        color: "red",
        atomicMass: "150.36",
        name: "Samarium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Eu",
        atomicNumber: 63,
        category: "lanthanide",
        color: "red",
        atomicMass: "151.96",
        name: "Europium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Gd",
        atomicNumber: 64,
        category: "lanthanide",
        color: "red",
        atomicMass: "157.25",
        name: "Gadolinium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tb",
        atomicNumber: 65,
        category: "lanthanide",
        color: "red",
        atomicMass: "158.93",
        name: "Terbium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Dy",
        atomicNumber: 66,
        category: "lanthanide",
        color: "red",
        atomicMass: "162.5",
        name: "Dysprosium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ho",
        atomicNumber: 67,
        category: "lanthanide",
        color: "red",
        atomicMass: "164.93",
        name: "Holmium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Er",
        atomicNumber: 68,
        category: "lanthanide",
        color: "red",
        atomicMass: "167.26",
        name: "Erbium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tm",
        atomicNumber: 69,
        category: "lanthanide",
        color: "red",
        atomicMass: "168.93",
        name: "Thulium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Yb",
        atomicNumber: 70,
        category: "lanthanide",
        color: "red",
        atomicMass: "173.05",
        name: "Ytterbium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Lu",
        atomicNumber: 71,
        category: "lanthanide",
        color: "red",
        atomicMass: "174.97",
        name: "Lutetium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 20,
    elements: [
      {
        symbol: "Ac",
        atomicNumber: 89,
        category: "actinide",
        color: "red",
        atomicMass: "227",
        name: "Actinium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Th",
        atomicNumber: 90,
        category: "actinide",
        color: "red",
        atomicMass: "232.04",
        name: "Thorium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pa",
        atomicNumber: 91,
        category: "actinide",
        color: "red",
        atomicMass: "231.04",
        name: "Protactinium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "U",
        atomicNumber: 92,
        category: "actinide",
        color: "red",
        atomicMass: "238.03",
        name: "Uranium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Np",
        atomicNumber: 93,
        category: "actinide",
        color: "red",
        atomicMass: "237",
        name: "Neptunium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pu",
        atomicNumber: 94,
        category: "actinide",
        color: "red",
        atomicMass: "244",
        name: "Plutonium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Am",
        atomicNumber: 95,
        category: "actinide",
        color: "red",
        atomicMass: "243",
        name: "Americium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cm",
        atomicNumber: 96,
        category: "actinide",
        color: "red",
        atomicMass: "247",
        name: "Curium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Bk",
        atomicNumber: 97,
        category: "actinide",
        color: "red",
        atomicMass: "247",
        name: "Berkelium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cf",
        atomicNumber: 98,
        category: "actinide",
        color: "red",
        atomicMass: "251",
        name: "Californium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Es",
        atomicNumber: 99,
        category: "actinide",
        color: "red",
        atomicMass: "252",
        name: "Einsteinium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Fm",
        atomicNumber: 100,
        category: "actinide",
        color: "red",
        atomicMass: "257",
        name: "Fermium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Md",
        atomicNumber: 101,
        category: "actinide",
        color: "red",
        atomicMass: "258",
        name: "Mendelevium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "No",
        atomicNumber: 102,
        category: "actinide",
        color: "red",
        atomicMass: "259",
        name: "Nobelium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Lr",
        atomicNumber: 103,
        category: "actinide",
        color: "red",
        atomicMass: "262",
        name: "Lawrencium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
];

export const groupsData = [
  {
    id: 1,
    elements: [
      {
        symbol: "H",
        atomicNumber: 1,
        category: "nonmetal",
        color: "green",
        atomicMass: "1.008",
        name: "Hydrogen",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Li",
        atomicNumber: 3,
        category: "alkali metal",
        color: "red",
        atomicMass: "6.94",
        name: "Lithium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Na",
        atomicNumber: 11,
        category: "alkali metal",
        color: "red",
        atomicMass: "22.990",
        name: "Sodium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "K",
        atomicNumber: 19,
        category: "alkali metal",
        color: "red",
        atomicMass: "39.098",
        name: "Potassium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rb",
        atomicNumber: 37,
        category: "alkali metal",
        color: "red",
        atomicMass: "85.468",
        name: "Rubidium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cs",
        atomicNumber: 55,
        category: "alkali metal",
        color: "red",
        atomicMass: "132.905",
        name: "Caesium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Fr",
        atomicNumber: 87,
        category: "alkali metal",
        color: "red",
        atomicMass: "(223)",
        name: "Francium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 2,
    elements: [
      {
        symbol: "Be",
        atomicNumber: 4,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "9.0122",
        name: "Beryllium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mg",
        atomicNumber: 12,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "24.305",
        name: "Magnesium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ca",
        atomicNumber: 20,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "40.078",
        name: "Calcium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sr",
        atomicNumber: 38,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "87.62",
        name: "Strontium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ba",
        atomicNumber: 56,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "137.327",
        name: "Barium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ra",
        atomicNumber: 88,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "(226)",
        name: "Radium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 3,
    elements: [
      {
        symbol: "Sc",
        atomicNumber: 21,
        category: "transition metal",
        color: "blue",
        atomicMass: "44.956",
        name: "Scandium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Y",
        atomicNumber: 39,
        category: "transition metal",
        color: "blue",
        atomicMass: "88.906",
        name: "Yttrium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "La",
        atomicNumber: "57-71",
        category: "lanthanides",
        color: "lightblue",
        atomicMass: "138.91",
        name: "Lanthanides",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ac",
        atomicNumber: "89-103",
        category: "actinide",
        color: "lightblue",
        atomicMass: "(227)",
        name: "Actinides",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 4,
    elements: [
      {
        symbol: "Ti",
        atomicNumber: 22,
        category: "transition metal",
        color: "blue",
        atomicMass: "47.867",
        name: "Titanium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Zr",
        atomicNumber: 40,
        category: "transition metal",
        color: "blue",
        atomicMass: "91.224",
        name: "Zirconium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Hf",
        atomicNumber: 72,
        category: "transition metal",
        color: "blue",
        atomicMass: "178.49",
        name: "Hafnium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rf",
        atomicNumber: 104,
        category: "transition metal",
        color: "blue",
        atomicMass: "(267)",
        name: "Rutherfordium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 5,
    elements: [
      {
        symbol: "V",
        atomicNumber: 23,
        category: "transition metal",
        color: "blue",
        atomicMass: "50.942",
        name: "Vanadium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Nb",
        atomicNumber: 41,
        category: "transition metal",
        color: "blue",
        atomicMass: "92.906",
        name: "Niobium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ta",
        atomicNumber: 73,
        category: "transition metal",
        color: "blue",
        atomicMass: "180.95",
        name: "Tantalum",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Db",
        atomicNumber: 105,
        category: "transition metal",
        color: "blue",
        atomicMass: "(270)",
        name: "Dubnium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 6,
    elements: [
      {
        symbol: "Cr",
        atomicNumber: 24,
        category: "transition metal",
        color: "blue",
        atomicMass: "51.996",
        name: "Chromium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mo",
        atomicNumber: 42,
        category: "transition metal",
        color: "blue",
        atomicMass: "95.95",
        name: "Molybdenum",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "W",
        atomicNumber: 74,
        category: "transition metal",
        color: "blue",
        atomicMass: "183.84",
        name: "Tungsten",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sg",
        atomicNumber: 106,
        category: "transition metal",
        color: "blue",
        atomicMass: "(271)",
        name: "Seaborgium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 7,
    elements: [
      {
        symbol: "Mn",
        atomicNumber: 25,
        category: "transition metal",
        color: "blue",
        atomicMass: "54.938",
        name: "Manganese",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tc",
        atomicNumber: 43,
        category: "transition metal",
        color: "blue",
        atomicMass: "(98)",
        name: "Technetium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Re",
        atomicNumber: 75,
        category: "transition metal",
        color: "blue",
        atomicMass: "186.21",
        name: "Rhenium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Bh",
        atomicNumber: 107,
        category: "transition metal",
        color: "blue",
        atomicMass: "(270)",
        name: "Bohrium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 8,
    elements: [
      {
        symbol: "Fe",
        atomicNumber: 26,
        category: "transition metal",
        color: "blue",
        atomicMass: "55.845",
        name: "Iron",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ru",
        atomicNumber: 44,
        category: "transition metal",
        color: "blue",
        atomicMass: "101.07",
        name: "Ruthenium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Os",
        atomicNumber: 76,
        category: "transition metal",
        color: "blue",
        atomicMass: "190.23",
        name: "Osmium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Hs",
        atomicNumber: 108,
        category: "transition metal",
        color: "blue",
        atomicMass: "(277)",
        name: "Hassium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 9,
    elements: [
      {
        symbol: "Co",
        atomicNumber: 27,
        category: "transition metal",
        color: "blue",
        atomicMass: "58.933",
        name: "Cobalt",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rh",
        atomicNumber: 45,
        category: "transition metal",
        color: "blue",
        atomicMass: "102.91",
        name: "Rhodium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ir",
        atomicNumber: 77,
        category: "transition metal",
        color: "blue",
        atomicMass: "192.22",
        name: "Iridium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mt",
        atomicNumber: 109,
        category: "transition metal",
        color: "blue",
        atomicMass: "(276)",
        name: "Meitnerium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 10,
    elements: [
      {
        symbol: "Ni",
        atomicNumber: 28,
        category: "transition metal",
        color: "blue",
        atomicMass: "58.693",
        name: "Nickel",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pd",
        atomicNumber: 46,
        category: "transition metal",
        color: "blue",
        atomicMass: "106.42",
        name: "Palladium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pt",
        atomicNumber: 78,
        category: "transition metal",
        color: "blue",
        atomicMass: "195.08",
        name: "Platinum",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ds",
        atomicNumber: 110,
        category: "transition metal",
        color: "blue",
        atomicMass: "(281)",
        name: "Darmstadtium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 11,
    elements: [
      {
        symbol: "Cu",
        atomicNumber: 29,
        category: "transition metal",
        color: "blue",
        atomicMass: "63.546",
        name: "Copper",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ag",
        atomicNumber: 47,
        category: "transition metal",
        color: "blue",
        atomicMass: "107.87",
        name: "Silver",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Au",
        atomicNumber: 79,
        category: "transition metal",
        color: "blue",
        atomicMass: "196.97",
        name: "Gold",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rg",
        atomicNumber: 111,
        category: "transition metal",
        color: "blue",
        atomicMass: "(282)",
        name: "Roentgenium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 12,
    elements: [
      {
        symbol: "Zn",
        atomicNumber: 30,
        category: "transition metal",
        color: "blue",
        atomicMass: "65.38",
        name: "Zinc",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cd",
        atomicNumber: 48,
        category: "transition metal",
        color: "blue",
        atomicMass: "112.41",
        name: "Cadmium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Hg",
        atomicNumber: 80,
        category: "transition metal",
        color: "blue",
        atomicMass: "200.59",
        name: "Mercury",
        stateAtRoomTemp: "liquid",
        state: "l",
      },
      {
        symbol: "Cn",
        atomicNumber: 112,
        category: "transition metal",
        color: "blue",
        atomicMass: "(285)",
        name: "Copernicium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 13,
    elements: [
      {
        symbol: "B",
        atomicNumber: 5,
        category: "metalloid",
        color: "yellow",
        atomicMass: "10.81",
        name: "Boron",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Al",
        atomicNumber: 13,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "26.982",
        name: "Aluminium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ga",
        atomicNumber: 31,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "69.723",
        name: "Gallium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "In",
        atomicNumber: 49,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "114.82",
        name: "Indium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tl",
        atomicNumber: 81,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "204.38",
        name: "Thallium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Nh",
        atomicNumber: 113,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "(286)",
        name: "Nihonium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 14,
    elements: [
      {
        symbol: "C",
        atomicNumber: 6,
        category: "nonmetal",
        color: "green",
        atomicMass: "12.011",
        name: "Carbon",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Si",
        atomicNumber: 14,
        category: "metalloid",
        color: "yellow",
        atomicMass: "28.085",
        name: "Silicon",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ge",
        atomicNumber: 32,
        category: "metalloid",
        color: "yellow",
        atomicMass: "72.63",
        name: "Germanium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sn",
        atomicNumber: 50,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "118.71",
        name: "Tin",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pb",
        atomicNumber: 82,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "207.2",
        name: "Lead",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Fl",
        atomicNumber: 114,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "(289)",
        name: "Flerovium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 15,
    elements: [
      {
        symbol: "N",
        atomicNumber: 7,
        category: "nonmetal",
        color: "green",
        atomicMass: "14.007",
        name: "Nitrogen",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "P",
        atomicNumber: 15,
        category: "nonmetal",
        color: "green",
        atomicMass: "30.974",
        name: "Phosphorus",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "As",
        atomicNumber: 33,
        category: "metalloid",
        color: "yellow",
        atomicMass: "74.922",
        name: "Arsenic",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sb",
        atomicNumber: 51,
        category: "metalloid",
        color: "yellow",
        atomicMass: "121.76",
        name: "Antimony",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Bi",
        atomicNumber: 83,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "208.98",
        name: "Bismuth",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mc",
        atomicNumber: 115,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "(288)",
        name: "Moscovium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 16,
    elements: [
      {
        symbol: "O",
        atomicNumber: 8,
        category: "nonmetal",
        color: "green",
        atomicMass: "15.999",
        name: "Oxygen",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "S",
        atomicNumber: 16,
        category: "nonmetal",
        color: "green",
        atomicMass: "32.06",
        name: "Sulfur",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Se",
        atomicNumber: 34,
        category: "nonmetal",
        color: "green",
        atomicMass: "78.971",
        name: "Selenium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Te",
        atomicNumber: 52,
        category: "metalloid",
        color: "yellow",
        atomicMass: "127.6",
        name: "Tellurium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Po",
        atomicNumber: 84,
        category: "metalloid",
        color: "yellow",
        atomicMass: "(209)",
        name: "Polonium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Lv",
        atomicNumber: 116,
        category: "post-transition metal",
        color: "purple",
        atomicMass: "(293)",
        name: "Livermorium",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 17,
    elements: [
      {
        symbol: "F",
        atomicNumber: 9,
        category: "halogen",
        color: "pink",
        atomicMass: "18.998",
        name: "Fluorine",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Cl",
        atomicNumber: 17,
        category: "halogen",
        color: "pink",
        atomicMass: "35.45",
        name: "Chlorine",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Br",
        atomicNumber: 35,
        category: "halogen",
        color: "pink",
        atomicMass: "79.904",
        name: "Bromine",
        stateAtRoomTemp: "liquid",
        state: "l",
      },
      {
        symbol: "I",
        atomicNumber: 53,
        category: "halogen",
        color: "pink",
        atomicMass: "126.9",
        name: "Iodine",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "At",
        atomicNumber: 85,
        category: "halogen",
        color: "pink",
        atomicMass: "(210)",
        name: "Astatine",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ts",
        atomicNumber: 117,
        category: "halogen",
        color: "pink",
        atomicMass: "(294)",
        name: "Tennessine",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 18,
    elements: [
      {
        symbol: "He",
        atomicNumber: 2,
        category: "noble gas",
        color: "cyan",
        atomicMass: "4.0026",
        name: "Helium",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Ne",
        atomicNumber: 10,
        category: "noble gas",
        color: "cyan",
        atomicMass: "20.18",
        name: "Neon",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Ar",
        atomicNumber: 18,
        category: "noble gas",
        color: "cyan",
        atomicMass: "39.948",
        name: "Argon",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Kr",
        atomicNumber: 36,
        category: "noble gas",
        color: "cyan",
        atomicMass: "83.798",
        name: "Krypton",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Xe",
        atomicNumber: 54,
        category: "noble gas",
        color: "cyan",
        atomicMass: "131.29",
        name: "Xenon",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Rn",
        atomicNumber: 86,
        category: "noble gas",
        color: "cyan",
        atomicMass: "(222)",
        name: "Radon",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Og",
        atomicNumber: 118,
        category: "noble gas",
        color: "cyan",
        atomicMass: "(294)",
        name: "Oganesson",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
];

export const columnData = [
  { id: 1, topValue: "G", bottomValue: "P" },
  { id: 2, periodNumber: 1 },
  { id: 3, periodNumber: 2 },
  { id: 4, periodNumber: 3 },
  { id: 5, periodNumber: 4 },
  { id: 6, periodNumber: 5 },
  { id: 7, periodNumber: 6 },
  { id: 8, periodNumber: 7 },
];
