export const LanthanidesActinidesSeries = [
  {
    id: 19,
    elements: [
      {
        symbol: "La",
        atomicNumber: 57,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "138.91",
        name: "Lanthanum",
        hindiName: "लैंथेनम",
        urduName: "لانیتھنم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ce",
        atomicNumber: 58,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "140.12",
        name: "Cerium",
        hindiName: "सेरियम",
        urduName: "سیریم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pr",
        atomicNumber: 59,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "140.91",
        name: "Praseodymium",
        hindiName: "प्रसीओडिमियम",
        urduName: "پراسيوڈيميوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Nd",
        atomicNumber: 60,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "144.24",
        name: "Neodymium",
        hindiName: "नियोडिमियम",
        urduName: "نيوڈيميم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pm",
        atomicNumber: 61,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "(145)",
        name: "Promethium",
        hindiName: "प्रोमेथियम",
        urduName: "پروميتيوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sm",
        atomicNumber: 62,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "150.36",
        name: "Samarium",
        hindiName: "सैमेरियम",
        urduName: "ساماريوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Eu",
        atomicNumber: 63,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "151.96",
        name: "Europium",
        hindiName: "यूरोपियम",
        urduName: "يوروپيوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Gd",
        atomicNumber: 64,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "157.25",
        name: "Gadolinium",
        hindiName: "गैडोलिनियम",
        urduName: "گيڈولينيوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tb",
        atomicNumber: 65,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "158.93",
        name: "Terbium",
        hindiName: "टर्बियम",
        urduName: "ٹيربيوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Dy",
        atomicNumber: 66,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "162.5",
        name: "Dysprosium",
        hindiName: "डिसप्रोसियम",
        urduName: "ڈسپروسيوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ho",
        atomicNumber: 67,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "164.93",
        name: "Holmium",
        hindiName: "होल्मियम",
        urduName: "ہولميوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Er",
        atomicNumber: 68,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "167.26",
        name: "Erbium",
        hindiName: "एरबियम",
        urduName: "اربيم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tm",
        atomicNumber: 69,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "168.93",
        name: "Thulium",
        hindiName: "थुलियम",
        urduName: "تھوليئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Yb",
        atomicNumber: 70,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "173.05",
        name: "Ytterbium",
        hindiName: "यटरबियम",
        urduName: "يٹربيئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Lu",
        atomicNumber: 71,
        category: "lanthanide",
        color: "#b5eecc",
        atomicMass: "174.97",
        name: "Lutetium",
        hindiName: "लुटेटियम",
        urduName: "لٹيٹيم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 20,
    elements: [
      {
        symbol: "Ac",
        atomicNumber: 89,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "227",
        name: "Actinium",
        hindiName: "ऐक्टिनियम",
        urduName: "ایکٹينيئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Th",
        atomicNumber: 90,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "232.04",
        name: "Thorium",
        hindiName: "थोरियम",
        urduName: "تھوريئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pa",
        atomicNumber: 91,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "231.04",
        name: "Protactinium",
        hindiName: "प्रोटैक्टिनियम",
        urduName: "پروٹیکٹينيئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "U",
        atomicNumber: 92,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "238.03",
        name: "Uranium",
        hindiName: "यूरेनियम",
        urduName: "يورينيم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Np",
        atomicNumber: 93,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "237",
        name: "Neptunium",
        hindiName: "नेप्ट्यूनियम",
        urduName: "نیپٹونيئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pu",
        atomicNumber: 94,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "244",
        name: "Plutonium",
        hindiName: "प्लूटोनियम",
        urduName: "پلوٹونيئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Am",
        atomicNumber: 95,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "243",
        name: "Americium",
        hindiName: "अमेरिसियम",
        urduName: "اميريشيم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cm",
        atomicNumber: 96,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "247",
        name: "Curium",
        hindiName: "क्यूरियम",
        urduName: "کيوريم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Bk",
        atomicNumber: 97,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "247",
        name: "Berkelium",
        hindiName: "बर्केलियम",
        urduName: "برکيلئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cf",
        atomicNumber: 98,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "251",
        name: "Californium",
        hindiName: "कैलिफ़ोर्नियम",
        urduName: "کيلفورنيئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Es",
        atomicNumber: 99,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "252",
        name: "Einsteinium",
        hindiName: "आइंस्टीनियम",
        urduName: "آئن سٹينيم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Fm",
        atomicNumber: 100,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "257",
        name: "Fermium",
        hindiName: "फर्मियम",
        urduName: "فرميئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Md",
        atomicNumber: 101,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "258",
        name: "Mendelevium",
        hindiName: "मेंडेलीवियम",
        urduName: "مينڈيليويم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "No",
        atomicNumber: 102,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "259",
        name: "Nobelium",
        hindiName: "नोबेलियम",
        urduName: "نوبيلئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Lr",
        atomicNumber: 103,
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "262",
        name: "Lawrencium",
        hindiName: "लॉरेंशियम",
        urduName: "لورينشيم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
];

export const groupsData = [
  {
    id: 1,
    elements: [
      {
        symbol: "H",
        atomicNumber: 1,
        category: "nonmetal",
        color: "#00ffff",
        atomicMass: "1.008",
        name: "Hydrogen",
        hindiName: "हाइड्रोजन",
        urduName: "ہائیڈروجن",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Li",
        atomicNumber: 3,
        category: "alkali metal",
        color: "#cbf0f8",
        atomicMass: "6.94",
        name: "Lithium",
        hindiName: "लिथियम",
        urduName: "لیتھیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Na",
        atomicNumber: 11,
        category: "alkali metal",
        color: "#cbf0f8",
        atomicMass: "22.990",
        name: "Sodium",
        hindiName: "सोडियम",
        urduName: "سوڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "K",
        atomicNumber: 19,
        category: "alkali metal",
        color: "#cbf0f8",
        atomicMass: "39.098",
        name: "Potassium",
        hindiName: "पोटैशियम",
        urduName: "پوٹاشیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rb",
        atomicNumber: 37,
        category: "alkali metal",
        color: "#cbf0f8",
        atomicMass: "85.468",
        name: "Rubidium",
        hindiName: "रूबिडियम",
        urduName: "روبڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cs",
        atomicNumber: 55,
        category: "alkali metal",
        color: "#cbf0f8",
        atomicMass: "132.905",
        name: "Caesium",
        hindiName: "सीज़ियम",
        urduName: "سیزیئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Fr",
        atomicNumber: 87,
        category: "alkali metal",
        color: "#cbf0f8",
        atomicMass: "(223)",
        name: "Francium",
        hindiName: "फ्रैंसियम",
        urduName: "فرانشیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 2,
    elements: [
      {
        symbol: "Be",
        atomicNumber: 4,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "9.0122",
        name: "Beryllium",
        hindiName: "बेरिलियम",
        urduName: "بیریلئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mg",
        atomicNumber: 12,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "24.305",
        name: "Magnesium",
        hindiName: "मैग्नीशियम",
        urduName: "میگنیشیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ca",
        atomicNumber: 20,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "40.078",
        name: "Calcium",
        hindiName: "कैल्शियम",
        urduName: "کیلشیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sr",
        atomicNumber: 38,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "87.62",
        name: "Strontium",
        hindiName: "स्ट्रोंटियम",
        urduName: "سٹرونٹیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ba",
        atomicNumber: 56,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "137.327",
        name: "Barium",
        hindiName: "बेरियम",
        urduName: "بیریم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ra",
        atomicNumber: 88,
        category: "alkaline earth metal",
        color: "orange",
        atomicMass: "(226)",
        name: "Radium",
        hindiName: "रेडियम",
        urduName: "ریڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 3,
    elements: [
      {
        symbol: "Sc",
        atomicNumber: 21,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "44.956",
        name: "Scandium",
        hindiName: "स्कैंडियम",
        urduName: "سکینڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Y",
        atomicNumber: 39,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "88.906",
        name: "Yttrium",
        hindiName: "यट्रियम",
        urduName: "اٹریئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "La",
        atomicNumber: "57-71",
        category: "lanthanides",
        color: "#b5eecc",
        atomicMass: "138.91",
        name: "Lanthanides",
        hindiName: "लैंथनाइड्स",
        urduName: "لینتھانیڈس",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ac",
        atomicNumber: "89-103",
        category: "actinide",
        color: "#ffc0c9",
        atomicMass: "(227)",
        name: "Actinides",
        hindiName: "ऐक्टिनाइड्स",
        urduName: "ایکٹینائیڈس",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 4,
    elements: [
      {
        symbol: "Ti",
        atomicNumber: 22,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "47.867",
        name: "Titanium",
        hindiName: "टाइटेनियम",
        urduName: "ٹائٹینیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Zr",
        atomicNumber: 40,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "91.224",
        name: "Zirconium",
        hindiName: "जिरकोनियम",
        urduName: "زرکونیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Hf",
        atomicNumber: 72,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "178.49",
        name: "Hafnium",
        hindiName: "हाफ्नियम",
        urduName: "ہافنیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rf",
        atomicNumber: 104,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(267)",
        name: "Rutherfordium",
        hindiName: "रदरफोर्डियम",
        urduName: "رتھر فورڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 5,
    elements: [
      {
        symbol: "V",
        atomicNumber: 23,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "50.942",
        name: "Vanadium",
        hindiName: "वैनडियम",
        urduName: "واناڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Nb",
        atomicNumber: 41,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "92.906",
        name: "Niobium",
        hindiName: "निओबियम",
        urduName: "نیوبیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ta",
        atomicNumber: 73,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "180.95",
        name: "Tantalum",
        hindiName: "टैंटलम",
        urduName: "ٹینٹلم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Db",
        atomicNumber: 105,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(268)",
        name: "Dubnium",
        hindiName: "डब्नियम",
        urduName: "ڈوبنیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 6,
    elements: [
      {
        symbol: "Cr",
        atomicNumber: 24,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "51.996",
        name: "Chromium",
        hindiName: "क्रोमियम",
        urduName: "کرومیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mo",
        atomicNumber: 42,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "95.95",
        name: "Molybdenum",
        hindiName: "मोलिब्डेनम",
        urduName: "مولیبدینم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "W",
        atomicNumber: 74,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "183.84",
        name: "Tungsten",
        hindiName: "टंग्स्टन",
        urduName: "ٹنکسٹن",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sg",
        atomicNumber: 106,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(269)",
        name: "Seaborgium",
        hindiName: "सीबॉर्गियम",
        urduName: "سیبورگیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 7,
    elements: [
      {
        symbol: "Mn",
        atomicNumber: 25,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "54.938",
        name: "Manganese",
        hindiName: "मैंगनीज",
        urduName: "مینگانیز",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tc",
        atomicNumber: 43,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(98)",
        name: "Technetium",
        hindiName: "टेक्नीशियम",
        urduName: "ٹیکنیٹیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Re",
        atomicNumber: 75,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "186.21",
        name: "Rhenium",
        hindiName: "रिनियम",
        urduName: "رینیئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Bh",
        atomicNumber: 107,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(270)",
        name: "Bohrium",
        hindiName: "बोह्रियम",
        urduName: "بوهريوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 8,
    elements: [
      {
        symbol: "Fe",
        atomicNumber: 26,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "55.845",
        name: "Iron",
        hindiName: "लोहा",
        urduName: "آئرن",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ru",
        atomicNumber: 44,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "101.07",
        name: "Ruthenium",
        hindiName: "रुथेनियम",
        urduName: "روتھینیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Os",
        atomicNumber: 76,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "190.23",
        name: "Osmium",
        hindiName: "ओस्मियम",
        urduName: "اوسمیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Hs",
        atomicNumber: 108,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(277)",
        name: "Hassium",
        hindiName: "हसियम",
        urduName: "ہاسیئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 9,
    elements: [
      {
        symbol: "Co",
        atomicNumber: 27,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "58.933",
        name: "Cobalt",
        hindiName: "कोबाल्ट",
        urduName: "کوبالٹ",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rh",
        atomicNumber: 45,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "102.91",
        name: "Rhodium",
        hindiName: "रोडियम",
        urduName: "روڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ir",
        atomicNumber: 77,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "192.22",
        name: "Iridium",
        hindiName: "इरिडियम",
        urduName: "ایریڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mt",
        atomicNumber: 109,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(278)",
        name: "Meitnerium",
        hindiName: "माइटनेरियम",
        urduName: "میٹنریم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 10,
    elements: [
      {
        symbol: "Ni",
        atomicNumber: 28,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "58.693",
        name: "Nickel",
        hindiName: "निकल",
        urduName: "نکل",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pd",
        atomicNumber: 46,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "106.42",
        name: "Palladium",
        hindiName: "पैलेडियम",
        urduName: "پیلیڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pt",
        atomicNumber: 78,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "195.08",
        name: "Platinum",
        hindiName: "प्लैटिनम",
        urduName: "پلاٹینم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ds",
        atomicNumber: 110,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(281)",
        name: "Darmstadtium",
        hindiName: "डार्मस्टेडटियम",
        urduName: "ڈارمسٹیڈٹیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 11,
    elements: [
      {
        symbol: "Cu",
        atomicNumber: 29,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "63.546",
        name: "Copper",
        hindiName: "तांबा",
        urduName: "تانبا",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ag",
        atomicNumber: 47,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "107.87",
        name: "Silver",
        hindiName: "चांदी",
        urduName: "چاندی",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Au",
        atomicNumber: 79,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "196.97",
        name: "Gold",
        hindiName: "सोना",
        urduName: "سونا",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Rg",
        atomicNumber: 111,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(282)",
        name: "Roentgenium",
        hindiName: "रोएंटजेनियम",
        urduName: "رینٹجینیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 12,
    elements: [
      {
        symbol: "Zn",
        atomicNumber: 30,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "65.38",
        name: "Zinc",
        hindiName: "जस्ता",
        urduName: "زنک",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Cd",
        atomicNumber: 48,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "112.41",
        name: "Cadmium",
        hindiName: "कैडमियम",
        urduName: "کیڈمیئم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Hg",
        atomicNumber: 80,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "200.59",
        name: "Mercury",
        hindiName: "पारा",
        urduName: "پارا",
        stateAtRoomTemp: "liquid",
        state: "l",
      },
      {
        symbol: "Cn",
        atomicNumber: 112,
        category: "transition metal",
        color: "#efdfc4",
        atomicMass: "(285)",
        name: "Copernicium",
        hindiName: "कोपर्निसियम",
        urduName: "کوپرنیشیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 13,
    elements: [
      {
        symbol: "B",
        atomicNumber: 5,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "10.81",
        name: "Boron",
        hindiName: "बोरॉन",
        urduName: "بوران",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Al",
        atomicNumber: 13,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "26.982",
        name: "Aluminium",
        hindiName: "एल्यूमिनियम",
        urduName: "ایلومینیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ga",
        atomicNumber: 31,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "69.723",
        name: "Gallium",
        hindiName: "गैलियम",
        urduName: "گیلیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "In",
        atomicNumber: 49,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "114.82",
        name: "Indium",
        hindiName: "इंडियम",
        urduName: "انڈیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Tl",
        atomicNumber: 81,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "204.38",
        name: "Thallium",
        hindiName: "थैलियम",
        urduName: "تھیلیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Nh",
        atomicNumber: 113,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "(286)",
        name: "Nihonium",
        hindiName: "निहोनियम",
        urduName: "نہونیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 14,
    elements: [
      {
        symbol: "C",
        atomicNumber: 6,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "12.011",
        name: "Carbon",
        hindiName: "कार्बन",
        urduName: "کاربن",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Si",
        atomicNumber: 14,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "28.085",
        name: "Silicon",
        hindiName: "सिलिकॉन",
        urduName: "سلیکان",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ge",
        atomicNumber: 32,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "72.63",
        name: "Germanium",
        hindiName: "जर्मेनियम",
        urduName: "جرمینیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sn",
        atomicNumber: 50,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "118.71",
        name: "Tin",
        hindiName: "टिन",
        urduName: "ٹن",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Pb",
        atomicNumber: 82,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "207.2",
        name: "Lead",
        hindiName: "सीसा",
        urduName: "لیڈ",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Fl",
        atomicNumber: 114,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "(289)",
        name: "Flerovium",
        hindiName: "फ्लेरोवियम",
        urduName: "فلروویم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 15,
    elements: [
      {
        symbol: "N",
        atomicNumber: 7,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "14.007",
        name: "Nitrogen",
        hindiName: "नाइट्रोजन",
        urduName: "نائٹروجن",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "P",
        atomicNumber: 15,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "30.974",
        name: "Phosphorus",
        hindiName: "फॉस्फोरस",
        urduName: "فاسفورس",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "As",
        atomicNumber: 33,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "74.922",
        name: "Arsenic",
        hindiName: "आर्सेनिक",
        urduName: "آرسینک",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Sb",
        atomicNumber: 51,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "121.76",
        name: "Antimony",
        hindiName: "एंटिमनी",
        urduName: "انٹمنی",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Bi",
        atomicNumber: 83,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "208.98",
        name: "Bismuth",
        hindiName: "बिस्मथ",
        urduName: "بسمتھ",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Mc",
        atomicNumber: 115,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "(290)",
        name: "Moscovium",
        hindiName: "मास्कोवियम",
        urduName: "ماسکوویم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 16,
    elements: [
      {
        symbol: "O",
        atomicNumber: 8,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "15.999",
        name: "Oxygen",
        hindiName: "ऑक्सीजन",
        urduName: "آکسیجن",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "S",
        atomicNumber: 16,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "32.06",
        name: "Sulfur",
        hindiName: "सल्फर",
        urduName: "گندھک",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Se",
        atomicNumber: 34,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "78.971",
        name: "Selenium",
        hindiName: "सेलेनियम",
        urduName: "سیلینیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Te",
        atomicNumber: 52,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "127.60",
        name: "Tellurium",
        hindiName: "टेल्यूरियम",
        urduName: "ٹیلیوریم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Po",
        atomicNumber: 84,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "(209)",
        name: "Polonium",
        hindiName: "पोलोनियम",
        urduName: "پولونیم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Lv",
        atomicNumber: 116,
        category: "post-transition metal",
        color: "#00ffff",
        atomicMass: "(293)",
        name: "Livermorium",
        hindiName: "लिवरमोरियम",
        urduName: "لیورموریوم",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 17,
    elements: [
      {
        symbol: "F",
        atomicNumber: 9,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "18.998",
        name: "Fluorine",
        hindiName: "फ्लोरीन",
        urduName: "فلورین",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Cl",
        atomicNumber: 17,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "35.45",
        name: "Chlorine",
        hindiName: "क्लोरीन",
        urduName: "کلورین",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Br",
        atomicNumber: 35,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "79.904",
        name: "Bromine",
        hindiName: "ब्रोमीन",
        urduName: "برومین",
        stateAtRoomTemp: "liquid",
        state: "l",
      },
      {
        symbol: "I",
        atomicNumber: 53,
        category: "nonmetal",
        color: "#cbf0f8",
        atomicMass: "126.90",
        name: "Iodine",
        hindiName: "आयोडीन",
        urduName: "آئوڈین",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "At",
        atomicNumber: 85,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "(210)",
        name: "Astatine",
        hindiName: "एस्टेटीन",
        urduName: "ایسٹاتین",
        stateAtRoomTemp: "solid",
        state: "s",
      },
      {
        symbol: "Ts",
        atomicNumber: 117,
        category: "metalloid",
        color: "#efdfc4",
        atomicMass: "(294)",
        name: "Tennessine",
        hindiName: "टेनेसीन",
        urduName: "ٹینیسیئن",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  },
  {
    id: 18,
    elements: [
      {
        symbol: "He",
        atomicNumber: 2,
        category: "noble gas",
        color: "yellow",
        atomicMass: "4.0026",
        name: "Helium",
        hindiName: "हीलियम",
        urduName: "ہیلیم",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Ne",
        atomicNumber: 10,
        category: "noble gas",
        color: "yellow",
        atomicMass: "20.180",
        name: "Neon",
        hindiName: "निऑन",
        urduName: "نیون",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Ar",
        atomicNumber: 18,
        category: "noble gas",
        color: "yellow",
        atomicMass: "39.95",
        name: "Argon",
        hindiName: "आर्गन",
        urduName: "آرگن",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Kr",
        atomicNumber: 36,
        category: "noble gas",
        color: "yellow",
        atomicMass: "83.798",
        name: "Krypton",
        hindiName: "क्रिप्टन",
        urduName: "کرپٹون",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Xe",
        atomicNumber: 54,
        category: "noble gas",
        color: "yellow",
        atomicMass: "131.29",
        name: "Xenon",
        hindiName: "जीनॉन",
        urduName: "زینون",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Rn",
        atomicNumber: 86,
        category: "noble gas",
        color: "yellow",
        atomicMass: "(222)",
        name: "Radon",
        hindiName: "रेडॉन",
        urduName: "ریڈون",
        stateAtRoomTemp: "gas",
        state: "g",
      },
      {
        symbol: "Og",
        atomicNumber: 118,
        category: "noble gas",
        color: "yellow",
        atomicMass: "(294)",
        name: "Oganesson",
        hindiName: "ओगनेसन",
        urduName: "اوگنیسن",
        stateAtRoomTemp: "solid",
        state: "s",
      },
    ],
  }
]

export const columnData = [
  { id: 1, topValue: "G", bottomValue: "P" },
  { id: 2, periodNumber: 1 },
  { id: 3, periodNumber: 2 },
  { id: 4, periodNumber: 3 },
  { id: 5, periodNumber: 4 },
  { id: 6, periodNumber: 5 },
  { id: 7, periodNumber: 6 },
  { id: 8, periodNumber: 7 },
];
